version: '2'

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    ports:9000
    restart:always
      
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /home/plex/nzbget/config:/config
      - /home/plex/Downloads:/downloads
      - /home/plex/Downloads/Complete:/downloads/complete
    ports:
      - 6789:6789
    restart: always
      
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    volumes:
      - /home/plex/plex:/config
      - /home/plex/Downloads/Complete/Movies:/movies
      - /home/plex/Downloads/Complete/Tvshows:/tvshows
    network_mode: host
    ports:
      - 32400:32400
    restart: always
    environment:
      - PLEX_CLAIM="<get from https://www.plex.tv/claim/>"
      
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /home/plex/plexpy:/config
      - /home/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    links:
      - plex
    restart: always
      
  watchtower:
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
